// Regression guard for SQLite quirks worked around in
// `lib/api/prisma_client.dart`:
//   * Auto-generated ids (no NULL PK).
//   * `bool` and `DateTime` arguments accepted by sqflite.
//   * `INSERT … RETURNING *` so `Delegate.create()` returns the row.

import 'package:flutter_test/flutter_test.dart';
import 'package:spieleabend/api/prisma_client.dart';

import '_helpers.dart';

void main() {
  initSqfliteFfi();

  test('auto-generated id, bool and DateTime args roundtrip', () async {
    final db = await openInMemoryPrismaClient();
    final u = await db.user.create(
      data: const CreateUserInput(username: 'iris', displayName: 'Iris'),
    );
    expect(
      u.id,
      isNotEmpty,
      reason: 'id must be auto-generated by SQLite default',
    );

    final g = await db.group.create(
      data: CreateGroupInput(name: 'X', createdById: u.id),
    );
    final scheduled = DateTime.utc(2030, 1, 2, 19, 30);
    final s = await db.gameSession.create(
      data: CreateGameSessionInput(
        groupId: g.id,
        scheduledAt: scheduled,
        hostId: u.id,
        location: 'here',
        finished: true,
      ),
    );
    expect(s.finished, isTrue);
    expect(s.scheduledAt.toUtc(), scheduled);
  });
}
